// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.AlgoritmoCompresion", b =>
                {
                    b.Property<int>("IdAlgoritmoCompresion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlgoritmoCompresion"));

                    b.Property<string>("NombreAlgoritmo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlgoritmoCompresion");

                    b.ToTable("AlgoritmosCompresion", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Comparacion", b =>
                {
                    b.Property<int>("IdComparacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComparacion"));

                    b.Property<DateTime>("FechaComparacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdImagenOriginal")
                        .HasColumnType("int");

                    b.Property<int>("IdImagenProcesada")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImagenDiferencias")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<float?>("MSE")
                        .HasColumnType("real");

                    b.Property<float?>("PSNR")
                        .HasColumnType("real");

                    b.HasKey("IdComparacion");

                    b.HasIndex("IdImagenOriginal");

                    b.HasIndex("IdImagenProcesada");

                    b.ToTable("Comparaciones", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Imagen", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<int>("AltoOriginal")
                        .HasColumnType("int");

                    b.Property<int>("AnchoOriginal")
                        .HasColumnType("int");

                    b.Property<byte[]>("DatosImagen")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdImagen");

                    b.ToTable("Imagenes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ImagenProcesada", b =>
                {
                    b.Property<int>("IdImagenProcesada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenProcesada"));

                    b.Property<int>("AltoResolucion")
                        .HasColumnType("int");

                    b.Property<int>("AnchoResolucion")
                        .HasColumnType("int");

                    b.Property<byte[]>("DatosProcesados")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaProcesamiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAlgoritmoCompresion")
                        .HasColumnType("int");

                    b.Property<int>("IdImagenOriginal")
                        .HasColumnType("int");

                    b.Property<byte>("ProfundidadBits")
                        .HasColumnType("tinyint");

                    b.Property<float?>("RatioCompresion")
                        .HasColumnType("real");

                    b.HasKey("IdImagenProcesada");

                    b.HasIndex("IdAlgoritmoCompresion");

                    b.HasIndex("IdImagenOriginal");

                    b.ToTable("ImagenesProcesadas", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ProfundidadBits", "[ProfundidadBits] IN (1,8,24)");
                        });
                });

            modelBuilder.Entity("Backend.Models.Comparacion", b =>
                {
                    b.HasOne("Backend.Models.Imagen", "ImagenOriginal")
                        .WithMany("ComparacionesOriginal")
                        .HasForeignKey("IdImagenOriginal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImagenProcesada", "ImagenProcesada")
                        .WithMany("Comparaciones")
                        .HasForeignKey("IdImagenProcesada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImagenOriginal");

                    b.Navigation("ImagenProcesada");
                });

            modelBuilder.Entity("Backend.Models.ImagenProcesada", b =>
                {
                    b.HasOne("Backend.Models.AlgoritmoCompresion", "AlgoritmoCompresion")
                        .WithMany("ImagenesProcesadas")
                        .HasForeignKey("IdAlgoritmoCompresion");

                    b.HasOne("Backend.Models.Imagen", "ImagenOriginal")
                        .WithMany("ImagenesProcesadas")
                        .HasForeignKey("IdImagenOriginal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlgoritmoCompresion");

                    b.Navigation("ImagenOriginal");
                });

            modelBuilder.Entity("Backend.Models.AlgoritmoCompresion", b =>
                {
                    b.Navigation("ImagenesProcesadas");
                });

            modelBuilder.Entity("Backend.Models.Imagen", b =>
                {
                    b.Navigation("ComparacionesOriginal");

                    b.Navigation("ImagenesProcesadas");
                });

            modelBuilder.Entity("Backend.Models.ImagenProcesada", b =>
                {
                    b.Navigation("Comparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
